sudo: required

branches:
  only:
    - master

language: node_js
node_js:
  - 7.2.1

cache:
  yarn: true

script:


after_success:
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - bash ./.travis.d/tag-version.sh
